language: python

cache:
  directories:
  - "$HOME/google-cloud-sdk/"

before_install:
  - openssl aes-256-cbc -K $encrypted_3f727974e704_key -iv $encrypted_3f727974e704_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xzf credentials.tar.gz
  - gcloud auth activate-service-account --key-file=key.json
  - gcloud config set project $PROJECT_NAME
  - gcloud config set container/cluster $CLUSTER_NAME
  - gcloud config set compute/zone $ZONE
  - gcloud container clusters get-credentials $CLUSTER_NAME --zone $ZONE
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then 
      rm -rf $HOME/google-cloud-sdk; 
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1; 
      curl https://sdk.cloud.google.com | bash; 
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components beta update
  - gcloud --quiet components update kubectl
