language: python

cache:
  directories:
  - "$HOME/google-cloud-sdk/"

script:
  - echo "$SERVICE_ACCOUNT_KEY" > key.json
  - gcloud auth activate-service-account --key-file=key.json
  - gcloud config set project $PROJECT_NAME
  - gcloud config set container/cluster $CLUSTER_NAME
  - gcloud config set compute/zone $ZONE
  - gcloud container clusters get-credentials $CLUSTER_NAME --zone $ZONE

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then 
      rm -rf $HOME/google-cloud-sdk; 
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1; 
      curl https://sdk.cloud.google.com | bash; 
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components beta update
  - gcloud --quiet components update kubectl

# deploy:
#   - provider: script
#     script: ./deploy-staging.sh
#     skip_cleanup: true
#     on:
#       branch: development
#   - provider: script
#     script: ./deploy-production.sh
#     skip_cleanup: true
#     on:
#       branch: master
